const aiInput = "80 + 21";
let str = aiInput.toLowerCase()
      .replace(/स्वरूप/g, '100')
      .replace(/सौ/g, '100')
      .replace(/हजार/g, '1000')
      .replace(/लाख/g, '100000')
      .replace(/एक/g, '1')
      .replace(/दो/g, '2')
      .replace(/तीन/g, '3')
      .replace(/चार/g, '4')
      .replace(/पांच/g, '5')
      .replace(/छह/g, '6')
      .replace(/सात/g, '7')
      .replace(/आठ/g, '8')
      .replace(/नौ/g, '9')
      .replace(/दस/g, '10')
      .replace(/వంద/g, '100')
      .replace(/వెయ్యి/g, '1000')
      .replace(/లక్ష/g, '100000')
      .replace(/ఒకటి|ఒక/g, '1')
      .replace(/రెండు/g, '2')
      .replace(/మూడు/g, '3')
      .replace(/నాలుగు/g, '4')
      .replace(/ఐదు/g, '5')
      .replace(/ఆరు/g, '6')
      .replace(/ఏడు/g, '7')
      .replace(/ఎనిమిది/g, '8')
      .replace(/తొమ్మిది/g, '9')
      .replace(/పది/g, '10')
      .replace(/plus/g, '+')
      .replace(/minus/g, '-')
      .replace(/times|multiplied by/g, '*')
      .replace(/divided by/g, '/')
      .replace(/percent/g, '%')
      .replace(/प्लस|और|जमा/g, '+')
      .replace(/माइनस|घटा/g, '-')
      .replace(/गुणा/g, '*')
      .replace(/भाग/g, '/')
      .replace(/प्रतिशत|परसेंट/g, '%')
      .replace(/ప్లస్|మరియు/g, '+')
      .replace(/మైనస్|తీసివేయి/g, '-')
      .replace(/ఇంటు|గుణకారం/g, '*')
      .replace(/భాగహారం/g, '/')
      .replace(/శాతం|పర్సెంట్/g, '%');

let mathStr = str.replace(/[a-z]/gi, '').trim();
const cleanMath = mathStr.replace(/[^0-9\+\-\*\/\.]/g, '');
console.log("cleanMath:", cleanMath);
